import type { Metadata } from "next";
import { Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/Navbar";

const notoSans = Noto_Sans_Bengali({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Assignment 07 - Bazar Dor",
  description: "Generated by Samrat Ahmed",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" data-theme="light">
      <body className={`min-h-full flex flex-col ${notoSans.className}`}>
        <Navbar />
        <div>{children}</div>
        <ToastContainer />
      </body>
    </html>
  );
}
